import type { Metadata } from "next";
import { Content, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Card from "./component/card/card";
import Home from "./component/home";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="fixed w-full top-0">
          <div className="flex gap-4 bg-stone-950 shadow-lg text-stone-200 z-100 px-10">
            <div className="flex items-center text-xl font-bold">
              <h1>UYE Archive</h1>
            </div>
            <div className="flex items-center">
              <ul className="flex">
                <li className="flex items-center px-2 border-l-2 border-red-500 hover:bg-red-500 duration-300">
                  <a href="" className="p-1 flex items-center">
                    <img src="https://img.icons8.com/material-outlined/50/web.png" alt="" className="w-7 p-0.5 rounded-full bg-stone-200 mr-2" />
                    Web
                  </a>
                </li>
                <li className="flex items-center px-2 border-l-2 border-red-500 hover:bg-red-500 duration-300">
                  <a href="" className="p-1 flex items-center">
                    <img src="https://img.icons8.com/material-outlined/50/book.png" alt="" className="w-7 p-0.5 rounded-full bg-stone-200 mr-2" />
                    Texts
                  </a>
                </li>
                <li className="flex items-center px-2 border-l-2 border-red-500 hover:bg-red-500 duration-300">
                  <a href="" className="p-1 flex items-center">
                    <img src="https://img.icons8.com/material-outlined/50/image.png" alt="" className="w-7 p-0.5 rounded-full bg-stone-200 mr-2" />
                    Images
                  </a>
                </li>
                <li className="flex items-center px-2 border-l-2 border-red-500 hover:bg-red-500 duration-300">
                  <a href="" className="p-1 flex items-center">
                    <img src="https://img.icons8.com/material-outlined/50/video.png" alt="" className="w-7 p-0.5 rounded-full bg-stone-200 mr-2" />
                    Videos
                  </a>
                </li>
              </ul>
            </div>
            <div className="flex items-center left-0 ml-auto">
              <a href="" className="p-1 flex items-center">
                <img src="https://img.icons8.com/material-outlined/50/moon.png" alt="" className="w-7 p-0.5 rounded-full bg-stone-200" />
              </a>
            </div>
          </div>

          <nav className="">
            <div>
              <ul className="flex text-xl bg-stone-900 text-stone-200 justify-center">
                <li className="px-6 hover:bg-red-500 duration-300">
                  <a href="a">About</a>
                </li>
                <li className="px-6 hover:bg-red-500 duration-300">
                  <a href="a">Project</a>
                </li>
                <li className="px-6 hover:bg-red-500 duration-300">
                  <a href="a">Contact</a>
                </li>
                <li className="px-6 hover:bg-red-500 duration-300">
                  <a href="a">Skill</a>
                </li>
              </ul>
            </div>
          </nav>
        </div>

        <Home />
        <Card />

        {children}
      </body>
    </html>
  );
}
