import type { Metadata } from "next";
import { Content, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Card from "./component/card/card";
import Home from "./component/home";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Top bars */}
        <div className="fixed inset-x-0 top-0 z-[100]">
          {/* Header */}
          <header className="mx-auto flex max-w-[1500px] items-center gap-4 bg-stone-950 px-10 text-stone-200">
            <img src="/uye-logo.png" className="w-12" alt="" />
            <h1 className="text-xl font-bold">UYE Archive</h1>

            {/* Primary nav (icon menu) */}
            <nav aria-label="primary" className="flex items-center">
              <ul className="flex border-l-2 border-red-500 divide-x-2 divide-red-500">
                <li className="px-2 duration-300 hover:bg-red-500">
                  <a href="" className="flex items-center p-1">
                    <img src="https://img.icons8.com/material-outlined/50/web.png" alt="" className="mr-2 w-7 rounded-full bg-stone-200 p-0.5" />
                    Web
                  </a>
                </li>
                <li className="px-2 duration-300 hover:bg-red-500">
                  <a href="" className="flex items-center p-1">
                    <img src="https://img.icons8.com/material-outlined/50/book.png" alt="" className="mr-2 w-7 rounded-full bg-stone-200 p-0.5" />
                    Texts
                  </a>
                </li>
                <li className="px-2 duration-300 hover:bg-red-500">
                  <a href="" className="flex items-center p-1">
                    <img src="https://img.icons8.com/material-outlined/50/image.png" alt="" className="mr-2 w-7 rounded-full bg-stone-200 p-0.5" />
                    Images
                  </a>
                </li>
                <li className="px-2 duration-300 hover:bg-red-500">
                  <a href="" className="flex items-center p-1">
                    <img src="https://img.icons8.com/material-outlined/50/video.png" alt="" className="mr-2 w-7 rounded-full bg-stone-200 p-0.5" />
                    Videos
                  </a>
                </li>
              </ul>
            </nav>

            {/* Theme toggle */}
            <div className="ml-auto flex items-center">
              <a href="" className="flex items-center p-1">
                <img src="https://img.icons8.com/material-outlined/50/moon.png" alt="" className="w-7 rounded-full bg-stone-200 p-0.5" />
              </a>
            </div>
          </header>

          {/* Secondary nav */}
          <nav aria-label="secondary">
            <ul className="flex justify-center bg-stone-900 text-xl text-stone-200">
              <li className="px-6 duration-300 hover:bg-red-500">
                <a href="a">About</a>
              </li>
              <li className="px-6 duration-300 hover:bg-red-500">
                <a href="a">Project</a>
              </li>
              <li className="px-6 duration-300 hover:bg-red-500">
                <a href="a">Contact</a>
              </li>
              <li className="px-6 duration-300 hover:bg-red-500">
                <a href="a">Skill</a>
              </li>
            </ul>
          </nav>
        </div>

        {children}
        <Home />
        <Card />
      </body>
    </html>
  );
}
